# Generated by Django 5.0.6 on 2024-06-01 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('parent_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('mesurement', models.CharField(choices=[('KG', 'Kg'), ('L', 'L'), ('PIECE', 'Piece'), ('TRANCHE', 'Tranche'), ('CONDIMENT', 'Condiment')], default='KG', max_length=10, verbose_name='Mesure')),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Prix moyen')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.category')),
                ('season', models.ManyToManyField(to='api.season')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeXEngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='Quantité')),
                ('age', models.CharField(choices=[('18+', 'Default'), ('Petit F', 'Pf'), ('Petit G', 'Pg'), ('Grand F', 'Gf'), ('Grand G', 'Gg')], default='18+', max_length=10, verbose_name="Tranche d'âge")),
                ('vege', models.BooleanField(default=False, verbose_name='Vege ?')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nom')),
                ('parent_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nom')),
                ('prairie', models.BooleanField(default=False, verbose_name='En prairie ?')),
                ('ingredients', models.ManyToManyField(to='api.recipexengredient')),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.tag')),
            ],
        ),
    ]
